name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: my-django-app

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker-compose -f docker-compose.yml build

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run web python manage.py test

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
